name: Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Flask app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP adress of the server to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of the server to ssh into
        
          script: |
            mkdir assignment_cd #create folder to deploy on the server
            cd assignment_cd #enter folder
            git clone git@github.com:WilcoSchuit/CD.git #Clone repository into folder
            echo 'Deployment successful to DigitalOcean' #Message to be displayed when deployment is successfull
          
